title: utala musi pi ma pona
description: >- # this means to ignore newlines until "url:"
  ma pona pi toki pona la utala musi li lon! o utala o lukin e musi pi tenpo pini!
# This is the list of links that show up at the top of the page using `lipu` template, adjust it with whatever (or none) links you would like
lawa:

toki:
  - tok
  - en
sona_ala_la_toki: tok
